SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE VIEW [dbo].[vw_ETL_IMPPRTM] AS  
SELECT 
    I#PART AS PN,
    I#PRTD AS Part_Desc,
    I#ORGD AS Origin_Date,
    I#ORDQ AS On_Ord_Qty,
    I#BOQT AS BO_Qty,
    I#CMQT AS Comm_Qty,
    I#ERQT AS Exp_Ret_Qty,
    I#ORDC AS Ord_Cntl,
    I#FRCM AS FM,
    I#SRCC AS Inplt_Src,
    I#NSTC AS Non_Stk_Code,
    I#AQCD AS Acq_Code,
    I#SCRT AS Scrap_Tag,
    I#NPGT AS No_Pkg_Tag,
    I#PKGC AS Package_Code,
    I#APKG AS Alt_Pkg_Info,
    I#CTVC AS Contact_Vend,
    I#PPCL AS Prm_Prod_Class,
    I#PPTY AS Prm_Prod_Type,
    I#NRPT AS New_Rep_Tag,
    I#PRTT AS Part_Type,
    I#VLDT AS Lead_Time,
    I#FLDT AS Fcst_LT,
    I#SLDT AS Spec_LT,
    I#NOLQ AS NIJ_Order_Limit_Qty,
    I#SOLQ AS SYD_Ord_Limit_Qty,
    I#3MOT AS Mo_Trans,
    I#SUSQ AS Physical_Inv_Usg,
    I#RTDC AS Physical_Inv_Rcpts,
    I#MAVQ AS Mo_Avg,
    I#MAD AS Safety_Stk,
    I#ORDP AS Ord_Point,
    I#EOQ AS EOQ,
    I#PKGQ AS Pkg_Qty,
    I#DSTG AS DS_Tag,
    I#CPCD AS Comb_Purch_Code,
    I#VNDC AS Vend_Code,
    I#CONS AS Cons_List,
    I#DLRN AS Dlr_Net,
    I#STDC AS Std_Cost,
    I#SOHQ AS SOH,
    I#CLCR AS Curr_Location,
    I#LOCT AS Loc_Tag,
    I#INVS AS Inv_Seg,
    I#PRDS AS Prod_Seg,
    I#MKTC AS Mkt_Class,
    I#INAD AS Inact_Date,
    I#PRDL AS Prod_Line,
    I#3MSL AS Item_3_Mo_Dlr_Usg,
    I#12MS AS Item_12_Mo_Dlr_Usg,
    I#12MU AS Item_12_Mo_IC_Usg,
    I#12MO AS Item_12_Mo_Ord,
    I#P3SL AS Pre_3_Mo_Dlr_Usg,
    I#P12S AS PRE_12_Mo_Dlr_Usg,
    I#P12U AS Pre_12_Mo_IC_Usg,
    I#P12O AS PRE_12_Mo_Ord,
    I#P3MO AS PRE_3_Mo_Ord,
    I#C3SL AS Comb_3_Mo_Dlr_Usg,
    I#C12S AS Comb_12_Mo_Dlr_Usg,
    I#C12U AS Comb_12_Mo_IC_Usg,
    I#C12O AS Comb_12_Mo_Ord,
    I#BRND AS Brand,
    I#COMM AS Commodity,
    I#MLCT AS MTD_Line_Ent,
    I#MLSH AS MTD_Line_Ship,
    I#12ML AS Line_Ent_12_Mo,
    I#12MC AS Line_Ship_12_Mo,
    I#12SO AS Stk_Out_12_Mo,
    I#STSC AS Status_Code,
    I#LRCD AS Last_Rcpt_Date,
    I#VPPO AS VOPS_PO,
    I#UNTC AS Unit_Code,
    I#CLF AS Class_Field,
    I#TRND AS Last_Tran_Date,
    I#RPLD AS Replaced_Date,
    I#ALCT AS Allocate_Date,
	I#SLSD AS SLS_Avail_Date,
    I#RSTG AS Re_Sourcing_Tag,
    I#CNGR AS CYC_ABC,
    I#CNQT AS HDLG_Cat,
    I#ALPH AS Alpha,
    I#STKP AS Stk_Part_Tag,
    I#INSC AS Inspect_Code,
    I#CURT AS Curr_Tag,
    I#CDTM AS Chg_Date_Time,
    COALESCE(Origin_cal.TheDate, NULL) AS Origin_dt,
    COALESCE(Inact_cal.TheDate, NULL) AS Inact_Dt,
    COALESCE(Last_Rcpt_cal.TheDate, NULL) AS Last_Rcpt_Dt,
    COALESCE(Last_Tran_cal.TheDate, NULL) AS Last_Tran_Dt,
    COALESCE(Replaced_cal.TheDate, NULL) AS Replaced_Dt,
    COALESCE(SLS_Avail_cal.TheDate, NULL) AS SLS_Avail_Dt 

FROM dwn_IMPPRTM

LEFT JOIN ref_Calendar AS Origin_cal ON dwn_IMPPRTM.I#ORGD = Origin_cal.CYYMMDD_7
LEFT JOIN ref_Calendar AS Inact_cal ON dwn_IMPPRTM.I#INAD = Inact_cal.CYYMMDD_7
LEFT JOIN ref_Calendar AS Last_Rcpt_cal ON dwn_IMPPRTM.I#LRCD = Last_Rcpt_cal.CYYMMDD_7
LEFT JOIN ref_Calendar AS Last_Tran_cal ON dwn_IMPPRTM.I#TRND = Last_Tran_cal.CYYMMDD_7
LEFT JOIN ref_Calendar AS Replaced_cal ON dwn_IMPPRTM.I#RPLD = Replaced_cal.CYYMMDD_7
LEFT JOIN ref_Calendar AS SLS_Avail_cal ON dwn_IMPPRTM.I#SLSD = SLS_Avail_cal.CYYMMDD_7;
GO
