SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO




CREATE VIEW [dbo].[ref_PDC_Complete_Part_Master_Legacy_Layout] AS
SELECT dbo.pdc_Part_Master.Part_No,
dbo.pdc_Part_Master.Part_Desc,
dbo.pdc_Part_Master.Origin_Date,
dbo.pdc_Part_Master.On_Ord_Qty,
dbo.pdc_Part_Master.BO_Qty,
dbo.pdc_Part_Master.Comm_Qty,
dbo.pdc_Part_Master.Exp_Ret_Qty,
dbo.pdc_Part_Master.Ord_Cntl,
dbo.pdc_Part_Master.FM,
dbo.pdc_Part_Master.Inplt_Src,
dbo.pdc_Part_Master.Non_Stk_Code,
dbo.pdc_Part_Master.Acq_Code,
dbo.pdc_Part_Master.Scrap_Tag,
dbo.pdc_Part_Master.No_Pkg_Tag,
dbo.pdc_Part_Master.Package_Code,
dbo.pdc_Part_Master.Alt_Pkg_Info,
dbo.pdc_Part_Master.Contact_Vend,
dbo.pdc_Part_Master.Prm_Prod_Class,
dbo.pdc_Part_Master.Prm_Prod_Type,
dbo.pdc_Part_Master.New_Rep_Tag,
dbo.pdc_Part_Master.Part_Type,
dbo.pdc_Part_Master.Lead_Time,
dbo.pdc_Part_Master.Fcst_LT,
dbo.pdc_Part_Master.Spec_LT, 
dbo.pdc_Part_Master.NIJ_Ord_Limit_Qty, 
dbo.pdc_Part_Master.SYD_Ord_Limit_Qty, 
dbo.pdc_Part_Master.[__Mo_Trans], 
dbo.pdc_Part_Master.Physical_Inv_Usg, 
dbo.pdc_Part_Master.Physical_Inv_Rcpts, 
dbo.pdc_Part_Master.Mo_Avg, 
dbo.pdc_Part_Master.Safety_Stk, 
dbo.pdc_Part_Master.Ord_Point, 
dbo.pdc_Part_Master.EOQ, 
dbo.pdc_Part_Master.Pkg_Qty, 
dbo.pdc_Part_Master.DS_Tag, 
dbo.pdc_Part_Master.Comb_Purch_Code, 
dbo.pdc_Part_Master.Vend_Code, 
dbo.pdc_Part_Master.Cons_List, 
dbo.pdc_Part_Master.Dlr_Net, 
dbo.pdc_Part_Master.Std_Cost, 
dbo.pdc_Part_Master.SOH, 
dbo.pdc_Part_Master.Curr_Location, 
dbo.pdc_Part_Master.Loc_Tag, 
dbo.pdc_Part_Master.Inv_Seg, 
dbo.pdc_Part_Master.Prod_Seg, 
dbo.pdc_Part_Master.Mkt_Class, 
dbo.pdc_Part_Master.Inact_Date, 
dbo.pdc_Part_Master.Prod_Line, 
dbo.pdc_Part_Master.Item_3_Mo_Dlr_Usg, 
dbo.pdc_Part_Master.Item_12_Mo_Dlr_Usg, 
dbo.pdc_Part_Master.Item_12_Mo_IC_Usg, 
dbo.pdc_Part_Master.Item_12_Mo_Ord, 
dbo.pdc_Part_Master.PRE_3_Mo_Dlr_Usg, 
dbo.pdc_Part_Master.PRE_12_Mo_Dlr_Usg, 
dbo.pdc_Part_Master.PRE_12_Mo_IC_Usg, 
dbo.pdc_Part_Master.PRE_12_Mo_Ord, 
dbo.pdc_Part_Master.PRE_3_Mo_Ord, 
dbo.pdc_Part_Master.Comb_3_Mo_Dlr_Usg, 
dbo.pdc_Part_Master.Comb_12_Mo_Dlr_Usg, 
dbo.pdc_Part_Master.Comb_12_Mo_IC_Usg, 
dbo.pdc_Part_Master.Comb_12_Mo_Ord, 
dbo.pdc_Part_Master.Brand, 
dbo.pdc_Part_Master.Commodity, 
dbo.pdc_Part_Master.MTD_Line_Ent, 
dbo.pdc_Part_Master.MTD_Line_Ship, 
dbo.pdc_Part_Master.[_2_Mo_Line_Ent], 
dbo.pdc_Part_Master.[_2_Mo_Line_Ship], 
dbo.pdc_Part_Master.[_2_Mo_Stk_Out], 
dbo.pdc_Part_Master.Status_Code, 
dbo.pdc_Part_Master.Last_Rcpt_Date, 
dbo.pdc_Part_Master.VOPS_PO, 
dbo.pdc_Part_Master.Unit_Code, 
dbo.pdc_Part_Master.Class_field, 
dbo.pdc_Part_Master.Last_Tran_Date, 
dbo.pdc_Part_Master.Replaced_Date, 
dbo.pdc_Part_Master.Allocate_Tag, 
dbo.pdc_Part_Master.Re_Sourcing_Tag,
dbo.pdc_Part_Master.SLS_Avail_Date, 
dbo.pdc_Part_Master.CYC_ABC, 
dbo.pdc_Part_Master.HDLG_Cat, 
dbo.pdc_Part_Master.Alpha, 
dbo.pdc_Part_Master.Stk_Part_Tag, 
dbo.pdc_Part_Master.Inspect_Code, 
dbo.pdc_Part_Master.Curr_Tag, 
dbo.pdc_Part_Master.Chg_Date_Time,
dbo.pdc_Part_Master.Origin_Dt,
dbo.pdc_Part_Master.Inact_Dt,
dbo.pdc_Part_Master.Last_Rcpt_Dt,
dbo.pdc_Part_Master.Last_Tran_Dt,
dbo.pdc_Part_Master.SLS_Avail_Dt
FROM dbo.pdc_Part_Master
UNION ALL 
SELECT dbo.pdc_Part_Master_INACT.Part_No,dbo.pdc_Part_Master_INACT.Part_Desc, dbo.pdc_Part_Master_INACT.Origin_Date, dbo.pdc_Part_Master_INACT.On_Ord_Qty, dbo.pdc_Part_Master_INACT.BO_Qty, dbo.pdc_Part_Master_INACT.Comm_Qty, dbo.pdc_Part_Master_INACT.Exp_Ret_Qty, dbo.pdc_Part_Master_INACT.Ord_Cntl, dbo.pdc_Part_Master_INACT.FM, dbo.pdc_Part_Master_INACT.Inplt_Src, dbo.pdc_Part_Master_INACT.Non_Stk_Code, dbo.pdc_Part_Master_INACT.Acq_Code, dbo.pdc_Part_Master_INACT.Scrap_Tag, dbo.pdc_Part_Master_INACT.No_Pkg_Tag, dbo.pdc_Part_Master_INACT.Package_Code, dbo.pdc_Part_Master_INACT.Alt_Pkg_Info, dbo.pdc_Part_Master_INACT.Contact_Vend, dbo.pdc_Part_Master_INACT.Prm_Prod_Class, dbo.pdc_Part_Master_INACT.Prm_Prod_Type, dbo.pdc_Part_Master_INACT.New_Rep_Tag, dbo.pdc_Part_Master_INACT.Part_Type, dbo.pdc_Part_Master_INACT.Lead_Time, dbo.pdc_Part_Master_INACT.Fcst_LT, dbo.pdc_Part_Master_INACT.Spec_LT, dbo.pdc_Part_Master_INACT.NIJ_Ord_Limit_Qty, dbo.pdc_Part_Master_INACT.SYD_Ord_Limit_Qty, dbo.pdc_Part_Master_INACT.[__Mo_Trans], dbo.pdc_Part_Master_INACT.Physical_Inv_Usg, dbo.pdc_Part_Master_INACT.Physical_Inv_Rcpts, dbo.pdc_Part_Master_INACT.Mo_Avg, dbo.pdc_Part_Master_INACT.Safety_Stk, dbo.pdc_Part_Master_INACT.Ord_Point, dbo.pdc_Part_Master_INACT.EOQ, dbo.pdc_Part_Master_INACT.Pkg_Qty, dbo.pdc_Part_Master_INACT.DS_Tag, dbo.pdc_Part_Master_INACT.Comb_Purch_Code, dbo.pdc_Part_Master_INACT.Vend_Code, dbo.pdc_Part_Master_INACT.Cons_List, dbo.pdc_Part_Master_INACT.Dlr_Net, dbo.pdc_Part_Master_INACT.Std_Cost, dbo.pdc_Part_Master_INACT.SOH, dbo.pdc_Part_Master_INACT.Curr_Location, dbo.pdc_Part_Master_INACT.Loc_Tag, dbo.pdc_Part_Master_INACT.Inv_Seg, dbo.pdc_Part_Master_INACT.Prod_Seg, dbo.pdc_Part_Master_INACT.Mkt_Class, dbo.pdc_Part_Master_INACT.Inact_Date, dbo.pdc_Part_Master_INACT.Prod_Line, dbo.pdc_Part_Master_INACT.Item_3_Mo_Dlr_Usg, dbo.pdc_Part_Master_INACT.Item_12_Mo_Dlr_Usg, dbo.pdc_Part_Master_INACT.Item_12_Mo_IC_Usg, dbo.pdc_Part_Master_INACT.Item_12_Mo_Ord, dbo.pdc_Part_Master_INACT.PRE_3_Mo_Dlr_Usg, dbo.pdc_Part_Master_INACT.PRE_12_Mo_Dlr_Usg, dbo.pdc_Part_Master_INACT.PRE_12_Mo_IC_Usg, dbo.pdc_Part_Master_INACT.PRE_12_Mo_Ord, dbo.pdc_Part_Master_INACT.PRE_3_Mo_Ord, dbo.pdc_Part_Master_INACT.Comb_3_Mo_Dlr_Usg, dbo.pdc_Part_Master_INACT.Comb_12_Mo_Dlr_Usg, dbo.pdc_Part_Master_INACT.Comb_12_Mo_IC_Usg, dbo.pdc_Part_Master_INACT.Comb_12_Mo_Ord, dbo.pdc_Part_Master_INACT.Brand, dbo.pdc_Part_Master_INACT.Commodity, dbo.pdc_Part_Master_INACT.MTD_Line_Ent, dbo.pdc_Part_Master_INACT.MTD_Line_Ship, dbo.pdc_Part_Master_INACT.[_2_Mo_Line_Ent], dbo.pdc_Part_Master_INACT.[_2_Mo_Line_Ship], dbo.pdc_Part_Master_INACT.[_2_Mo_Stk_Out], dbo.pdc_Part_Master_INACT.Status_code, dbo.pdc_Part_Master_INACT.Last_Rcpt_Date, dbo.pdc_Part_Master_INACT.VOPS_PO, dbo.pdc_Part_Master_INACT.Unit_code, dbo.pdc_Part_Master_INACT.Class_field, dbo.pdc_Part_Master_INACT.Last_Tran_Date, Null AS Replaced_Date, Null AS Allocate_Tag, dbo.pdc_Part_Master_INACT.Re_Source_Tag AS Re_Sourcing_Tag, dbo.pdc_Part_Master_INACT.Sls_Avail_Date, Null AS CYC_ABC, Null AS HDLG_Cat, dbo.pdc_Part_Master_INACT.Alpha_Code AS Alpha, Null AS Stk_Part_Tag, Null AS Inspect_Code, Null AS Curr_Tag, dbo.pdc_Part_Master_INACT.Chg_Date_Time,dbo.pdc_Part_Master_INACT.Origin_Dt,dbo.pdc_Part_Master_INACT.Inact_Dt,dbo.pdc_Part_Master_INACT.Last_Rcpt_Dt,dbo.pdc_Part_Master_INACT.Last_Tran_Dt,dbo.pdc_Part_Master_INACT.SLS_Avail_Dt
FROM dbo.pdc_Part_Master_Inact

GO
