SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE VIEW [dbo].[ref_PDC_Part_Detail] AS

SELECT DISTINCT [PN]
      ,[Desc]
      ,[Comm]
      ,[Combi]
      ,[Alpha]
      ,[SOH]
      ,[PreRcpt]
      ,[OO]
      ,[SS]
      ,[BO]
      ,[Commtd]
      ,[12_Mo_Usg]
      ,[12_Mo_Trans]
      ,[MTD_LE]
      ,[MTD_LF]
      ,[12_Mo_LE]
      ,[12_Mo_LF]
      ,[Lst_Rcpt_Dt]
      ,[Lst_Tran_Dt]
      ,[Origin_Dt]
      ,[Inact_Dt]
      ,[SLS_Dt]
      ,[Status]
      ,[Vend]
      ,[ContactVend]
      ,[New_Rep]
      ,[Inplt_Src]
	  ,[RSTag]
	  ,[InspTag]
      ,[DS]
      ,[NsCd]
      ,[PrdCls]
      ,[PrdTyp]
      ,[StdCst]
      ,[DlrNet]
	  ,[CnsLst]
      ,[OP]
      ,[EOQ]
	  ,[PrtType]
      ,[OC]
      ,[SC]
	  ,[PkgCd]
	  ,[PkgQty]
      ,[Set_Alpha]
      ,[Set_SOH]
      ,[Set_PreRcpt]
      ,[Set_OO]
      ,[Set_SS]
      ,[Set_BO]
      ,[Set_Commtd]
      ,[Set_12_Mo_Usg]
      ,[Set_12_Mo_Trans]
      ,[Set_MTD_LE]
      ,[Set_MTD_LF]
      ,[Set_12_Mo_LE]
      ,[Set_12_Mo_LF]
      ,[Set_Lst_Rcpt_Dt]
      ,[Set_Lst_Tran_Dt]
      ,[Set_Mo_Av]
      ,[Set_Ld_Time]
      ,[Set_Vend]
	  ,[SPN]
  FROM [dbo].[ref_PDC_Part_Set_Detail]

GO
