CREATE TABLE [dbo].[zref_PDC_Proj_Tracking_Test]
(
[Proj] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[IA] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SetID] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[PN] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Desc] [varchar] (22) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SetAlpha] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NewRplcng] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SetLstRcptDt] [date] NULL,
[OC] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SC] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProjImplDt] [date] NULL,
[ProjRelDt] [date] NULL,
[NeedDt] [date] NULL,
[SlsDt] [date] NULL,
[VendDt] [date] NULL,
[OriginDt] [date] NULL,
[RSTg] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DSTg] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SetSOH] [float] NULL,
[SetPreRcpt] [float] NULL,
[SetOO] [float] NULL,
[SetBO] [float] NULL,
[SetSS] [float] NULL,
[SetMoAv] [float] NULL,
[SetLdTime] [float] NULL,
[Combi] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SetVC] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PRSVend] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Vendor] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Byr] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StdCst] [float] NULL,
[Set12MoLE] [float] NULL,
[Set12MoLF] [float] NULL,
[SetMTDLE] [float] NULL,
[SetMTDLF] [float] NULL,
[InactDt] [date] NULL,
[1stPO] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[1stPODueDate] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[1stPOConfCd] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[1stPOReqDate] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[1stPOOpenOrderQty] [float] NULL,
[1stPOPreRcptDate] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[1stPOPreRcptQty] [float] NULL,
[TotPOPreRcptQty] [float] NULL
) ON [PRIMARY]
GO
