CREATE TABLE [dbo].[ref_PDC_SPN_AMDC_PN_XPN]
(
[Hyster] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Yale] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Ignore] [nchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ref_PDC_SPN_AMDC_PN_XPN] ADD CONSTRAINT [PK_ref_PDC_SPN_AMDC_PN_XPN] PRIMARY KEY CLUSTERED ([Hyster], [Yale]) ON [PRIMARY]
GO
GRANT INSERT ON  [dbo].[ref_PDC_SPN_AMDC_PN_XPN] TO [GLOBAL\apcsexto]
GO
GRANT REFERENCES ON  [dbo].[ref_PDC_SPN_AMDC_PN_XPN] TO [GLOBAL\apcsexto]
GO
GRANT SELECT ON  [dbo].[ref_PDC_SPN_AMDC_PN_XPN] TO [GLOBAL\apcsexto]
GO
GRANT UPDATE ON  [dbo].[ref_PDC_SPN_AMDC_PN_XPN] TO [GLOBAL\apcsexto]
GO
GRANT DELETE ON  [dbo].[ref_PDC_SPN_AMDC_PN_XPN] TO [GLOBAL\apjdudle]
GO
GRANT INSERT ON  [dbo].[ref_PDC_SPN_AMDC_PN_XPN] TO [GLOBAL\apjdudle]
GO
GRANT SELECT ON  [dbo].[ref_PDC_SPN_AMDC_PN_XPN] TO [GLOBAL\apjdudle]
GO
GRANT UPDATE ON  [dbo].[ref_PDC_SPN_AMDC_PN_XPN] TO [GLOBAL\apjdudle]
GO
GRANT DELETE ON  [dbo].[ref_PDC_SPN_AMDC_PN_XPN] TO [GLOBAL\aprlong]
GO
GRANT INSERT ON  [dbo].[ref_PDC_SPN_AMDC_PN_XPN] TO [GLOBAL\aprlong]
GO
GRANT SELECT ON  [dbo].[ref_PDC_SPN_AMDC_PN_XPN] TO [GLOBAL\aprlong]
GO
GRANT UPDATE ON  [dbo].[ref_PDC_SPN_AMDC_PN_XPN] TO [GLOBAL\aprlong]
GO
