CREATE TABLE [dbo].[dwn_eng_ECN]
(
[ABABCD] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ABAADT] [float] NOT NULL,
[ABABTX] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ABACTX] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ABABST] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ABACST] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ABADST] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ABADTX] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ABAETX] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ABAEST] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ABAFST] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ABADCD] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ABAECD] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ABAGST] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ABAHST] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ABAIST] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ABAJST] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ABAKST] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ABALST] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ABAMST] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ABANST] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ABAOST] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ABAPST] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ABAQST] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ABARST] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ABASST] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ABATST] [float] NOT NULL,
[ABAUST] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ABAVST] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ABAWST] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ABAXST] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ABEIST] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ABGKST] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ABIMST] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ABKMST] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ABE7TX] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ABCENA] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ABM7ST] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ABOBST] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ABOCST] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ABODST] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ABOEST] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ABCODT] [float] NOT NULL,
[ABCPDT] [float] NOT NULL,
[ABCQDT] [float] NOT NULL,
[ABCRDT] [float] NOT NULL,
[ABUKST] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ABJCCD] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ABC4CD] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ABBRCD] [float] NOT NULL
) ON [PRIMARY]
GO
