CREATE TABLE [dbo].[dwn_eng_VIP]
(
[AJATCD] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[AJBLCD] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[AJA4ST] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[AJA5ST] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[AJAUCD] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[AJADDT] [float] NOT NULL,
[AJAXCD] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[AJAYCD] [varchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[AJA6ST] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[AJAEDT] [float] NOT NULL,
[AJAZCD] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[AJA0CD] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[AJA7ST] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[AJA1CD] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[AJA2CD] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[AJA8ST] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[AJA3CD] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[AJAFDT] [float] NOT NULL,
[AJA9ST] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[AJA4CD] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[AJAGDT] [float] NOT NULL,
[AJA5CD] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[AJA0TX] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[AJA1TX] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[AJA2TX] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[AJA3TX] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[AJEJST] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[AJFAST] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[AJFCST] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[AJFNST] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[AJBPDT] [float] NOT NULL,
[AJKUST] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[AJUOST] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[AJA8CD] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
