CREATE TABLE [dbo].[res_Kit_BOM]
(
[Brand] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Maint_Date] [date] NULL,
[PN] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[COMM1] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comp_1] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comp_1_Qty] [decimal] (18, 0) NULL,
[Comp_2] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comp_2_qty] [decimal] (18, 0) NULL,
[Comp_3] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comp_3_Qty] [decimal] (18, 0) NULL,
[Comp_4] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comp_4_Qty] [decimal] (18, 0) NULL,
[Comp_5] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comp_5_Qty] [decimal] (18, 0) NULL,
[Comp_6] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comp_6_Qty] [decimal] (18, 0) NULL,
[Comp_7] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comp_7_qty] [decimal] (18, 0) NULL,
[Comp_8] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comp_8_Qty] [decimal] (18, 0) NULL,
[Comp_9] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comp_9_Qty] [decimal] (18, 0) NULL,
[Comp_10] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comp_10_Qty] [decimal] (18, 0) NULL,
[Comp_11] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comp_11_qty] [decimal] (18, 0) NULL,
[Comp_12] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comp_12_Qty] [decimal] (18, 0) NULL,
[Comp_13] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comp_13_Qty] [decimal] (18, 0) NULL,
[Comp_14] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comp_14_Qty] [decimal] (18, 0) NULL,
[Comp_15] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comp_15_Qty] [decimal] (18, 0) NULL,
[Comp_16] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comp_16_qty] [decimal] (18, 0) NULL,
[Comp_17] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comp_17_Qty] [decimal] (18, 0) NULL,
[Comp_18] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comp_18_qty] [decimal] (18, 0) NULL,
[Comp_19] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comp_19_Qty] [decimal] (18, 0) NULL,
[Comp_20] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comp_20_Qty] [decimal] (18, 0) NULL,
[Comp_21] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comp_21_qty] [decimal] (18, 0) NULL,
[Comp_22] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comp_22_Qty] [decimal] (18, 0) NULL,
[Comp_23] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comp_23_Qty] [decimal] (18, 0) NULL,
[Comp_24] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comp_24_Qty] [decimal] (18, 0) NULL,
[Comp_25] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comp_25_Qty] [decimal] (18, 0) NULL,
[Comp_26] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comp_26_qty] [decimal] (18, 0) NULL,
[Comp_27] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comp_27_Qty] [decimal] (18, 0) NULL,
[Comp_28] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comp_28_qty] [decimal] (18, 0) NULL,
[Comp_29] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comp_29_Qty] [decimal] (18, 0) NULL,
[Comp_30] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comp_30_Qty] [decimal] (18, 0) NULL,
[Comp_31] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comp_31_qty] [decimal] (18, 0) NULL,
[Comp_32] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comp_32_Qty] [decimal] (18, 0) NULL,
[Comp_33] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comp_33_Qty] [decimal] (18, 0) NULL,
[Comp_34] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comp_34_Qty] [decimal] (18, 0) NULL,
[Comp_35] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comp_35_Qty] [decimal] (18, 0) NULL,
[Comp_36] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comp_36_qty] [decimal] (18, 0) NULL,
[Comp_37] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comp_37_Qty] [decimal] (18, 0) NULL,
[Comp_38] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comp_38_qty] [decimal] (18, 0) NULL,
[Comp_39] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comp_39_Qty] [decimal] (18, 0) NULL,
[Comp_40] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comp_40_Qty] [decimal] (18, 0) NULL,
[Comp_41] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comp_41_qty] [decimal] (18, 0) NULL,
[Comp_42] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comp_42_Qty] [decimal] (18, 0) NULL,
[Comp_43] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comp_43_Qty] [decimal] (18, 0) NULL,
[Comp_44] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comp_44_Qty] [decimal] (18, 0) NULL,
[Comp_45] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comp_45_Qty] [decimal] (18, 0) NULL,
[Comp_46] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comp_46_qty] [decimal] (18, 0) NULL,
[Comp_47] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comp_47_Qty] [decimal] (18, 0) NULL,
[Comp_48] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comp_48_qty] [decimal] (18, 0) NULL,
[Comp_49] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comp_49_Qty] [decimal] (18, 0) NULL,
[Comp_50] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comp_50_Qty] [decimal] (18, 0) NULL,
[COMM2] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[COMM3] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[COMM4] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[COMM5] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[COMM6] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[COMM7] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[COMM8] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[COMM9] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[COMM10] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[COMM11] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[COMM12] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[COMM13] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[COMM14] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[COMM15] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[COMM16] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[COMM17] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[COMM18] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[COMM19] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[COMM20] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[COMP1 COMM] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[COMP2 COMM] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[COMP3 COMM] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[COMP4 COMM] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[COMP5 COMM] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[COMP6 COMM] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[COMP7 COMM] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[COMP8 COMM] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ASM L-# IN] [decimal] (7, 2) NULL,
[ALT BUILD] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[res_Kit_BOM] ADD CONSTRAINT [PK_res_Kit_BOM] PRIMARY KEY CLUSTERED ([PN]) ON [PRIMARY]
GO
