CREATE TABLE [dbo].[wrk_RYOS_PDC_PN_in_CORE]
(
[PN] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[wrk_RYOS_PDC_PN_in_CORE] ADD CONSTRAINT [PK_ryos_in_CORE_tmp] PRIMARY KEY CLUSTERED ([PN]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [NonClusteredIndex-20220224-202709] ON [dbo].[wrk_RYOS_PDC_PN_in_CORE] ([PN]) ON [PRIMARY]
GO
