CREATE TABLE [dbo].[wrk_RYOS_PDC_RYOS]
(
[PN] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[RYOS] [numeric] (4, 1) NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[wrk_RYOS_PDC_RYOS] ADD CONSTRAINT [PK_ryos_ryos_tmp] PRIMARY KEY CLUSTERED ([PN]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_ryos_ryos_tmp] ON [dbo].[wrk_RYOS_PDC_RYOS] ([PN]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [NonClusteredIndex-20220224-203551] ON [dbo].[wrk_RYOS_PDC_RYOS] ([PN]) ON [PRIMARY]
GO
