CREATE TABLE [dbo].[dwn_IMPWLOC2]
(
[IPWHS] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[IPAISL] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[IPBAY] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[IPLEVL] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[IPSTOR] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[IPLOCS] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[IPCKDG] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[IPPCKV] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[IPPUTV] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[IPMVCC] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[IPPCKZ] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[IPPUTZ] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[IPCNTY] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[IPCMPY] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[IPITEM] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[IPISTA] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[IPEUM1] [int] NOT NULL,
[IPUOML] [float] NOT NULL,
[IPUOMH] [float] NOT NULL,
[IPUOMW] [float] NOT NULL,
[IPUOWE] [float] NOT NULL,
[IPCPCK] [int] NOT NULL,
[IPLCAS] [float] NOT NULL,
[IPHCAS] [float] NOT NULL,
[IPWIDC] [float] NOT NULL,
[IPWEIC] [float] NOT NULL,
[IPUOM2] [int] NOT NULL,
[IP2LNG] [float] NOT NULL,
[IP2HEG] [float] NOT NULL,
[IP2WID] [float] NOT NULL,
[IP2WEI] [float] NOT NULL,
[IPECPL] [int] NOT NULL,
[IPLNGP] [float] NOT NULL,
[IPHEPL] [float] NOT NULL,
[IPWDPL] [float] NOT NULL,
[IPPLWT] [float] NOT NULL,
[IPPIEC] [int] NOT NULL,
[IPNODS] [int] NOT NULL,
[IPOHQT] [int] NOT NULL,
[IPITQT] [int] NOT NULL,
[IPRCQT] [int] NOT NULL,
[IPAQTY] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[IPADTE] [int] NOT NULL,
[IPEDTE] [int] NOT NULL,
[IPLFRZ] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[IPCYCE] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[IPALLZ] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[IPLOTC] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[IPLOTN] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[IPLOTS] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[IPDTCR] [int] NOT NULL,
[IPSTUM] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[IPPRML] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[IPLAST] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
