CREATE TABLE [dbo].[dwn_IMPVNA]
(
[VCVNCD] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[V1VNAM] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[V1ADR1] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[V1ADR2] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[V1ADR3] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[V1TXCD] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[V1SITC] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[V1FOB] [varchar] (11) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[V1ZPCD] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[V1BYRC] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[V1LACD] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[V1SHP6] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[V1VMIN] [int] NOT NULL,
[V1TRMC] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[V1PYV6] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[V1PKGC] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[V1OVVN] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[V1PHNE] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[V1MMST] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[V1DSHT] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[V1CRNC] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[V1MXPR] [float] NOT NULL,
[V1TRND] [float] NOT NULL,
[V1EXRN] [float] NOT NULL,
[V1HGVL] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[V1CMVN] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[V1IACD] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[V1TRTP] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[V1FMTP] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[V1NBLN] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[V1INDT] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[V1PYBL] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[V1MINR] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[V1PRT2] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[VCTYPO] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[V1LST] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
