CREATE TABLE [dbo].[wrk_RYOS_PDC_Tooling_Die]
(
[VPN_Die] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[wrk_RYOS_PDC_Tooling_Die] ADD CONSTRAINT [PK_ryos_die_tmp] PRIMARY KEY CLUSTERED ([VPN_Die]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [NonClusteredIndex-20220224-202447] ON [dbo].[wrk_RYOS_PDC_Tooling_Die] ([VPN_Die]) ON [PRIMARY]
GO
