CREATE TABLE [dbo].[dwn_eng_ECN_Part_Tran]
(
[B8ABCD] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[B8B4CD] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[B8B5CD] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[B8CETX] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[B8CFTX] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[B8FCCD] [varchar] (22) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[B8HZST] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[B8H0ST] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[B8FDCD] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[B8DANB] [float] NOT NULL,
[B8DBNB] [float] NOT NULL,
[B8FECD] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[B8FFCD] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[B8FGCD] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[B8DCNB] [float] NOT NULL,
[B8A9DT] [float] NOT NULL,
[B8H1ST] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[B8H2ST] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[B8FHCD] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[B8FICD] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[B8BADT] [float] NOT NULL,
[B8FJCD] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[B8H3ST] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[B8H4ST] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[B8D1TX] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[B8D2TX] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[B8D3TX] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[B8H5ST] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[B8BBDT] [float] NOT NULL,
[B8DDNB] [float] NOT NULL,
[B8EJTX] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[B8F4CD] [varchar] (22) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[B8JIST] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[B8J0ST] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[B8G0CD] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[B8K0ST] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[B8K1ST] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[B8K2ST] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[B8K3ST] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[B8K4ST] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[B8K5ST] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[B8K6ST] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[B8K7ST] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[B8K8ST] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[B8NBST] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[B8SGST] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[B8IXNB] [float] NOT NULL,
[B8K2TX] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[B8UMST] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
