CREATE TABLE [dbo].[ref_Calendar]
(
[TheDate] [date] NOT NULL,
[TheDay] [int] NULL,
[TheDaySuffix] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TheDayName] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TheDayOfWeek] [int] NULL,
[TheDayOfWeekInMonth] [tinyint] NULL,
[TheDayOfYear] [int] NULL,
[IsWeekend] [int] NOT NULL,
[TheWeek] [int] NULL,
[TheISOweek] [int] NULL,
[TheFirstOfWeek] [date] NULL,
[TheLastOfWeek] [date] NULL,
[TheWeekOfMonth] [tinyint] NULL,
[TheMonth] [int] NULL,
[TheMonthName] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TheMonthNameYear] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TheFirstOfMonth] [date] NULL,
[TheLastOfMonth] [date] NULL,
[TheFirstOfNextMonth] [date] NULL,
[TheLastOfNextMonth] [date] NULL,
[TheQuarter] [int] NULL,
[TheFirstOfQuarter] [date] NULL,
[TheLastOfQuarter] [date] NULL,
[TheYear] [int] NULL,
[TheISOYear] [int] NULL,
[TheFirstOfYear] [date] NULL,
[TheLastOfYear] [date] NULL,
[IsLeapYear] [bit] NULL,
[Has53Weeks] [int] NOT NULL,
[Has53ISOWeeks] [int] NOT NULL,
[MMYYYY] [char] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CYYMMDD] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CYYMMDD_7] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[YYYYMMDD] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[YYMMDD] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MMDDYY] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Style101] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Style103] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Style112] [char] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Style120] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
