CREATE TABLE [dbo].[zref_PDC_Part_Set_Detail_Test]
(
[PN] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Desc] [varchar] (22) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comm] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Combi] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Alpha] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SOH] [float] NOT NULL,
[PreRcpt] [float] NOT NULL,
[OO] [float] NOT NULL,
[SS] [float] NOT NULL,
[BO] [float] NOT NULL,
[Commtd] [float] NOT NULL,
[12_Mo_Usg] [float] NULL,
[12_Mo_Trans] [float] NULL,
[MTD_LE] [float] NOT NULL,
[MTD_LF] [float] NOT NULL,
[12_Mo_LE] [float] NOT NULL,
[12_Mo_LF] [float] NOT NULL,
[Lst_Rcpt_Dt] [date] NULL,
[Lst_Tran_Dt] [date] NULL,
[Origin_Dt] [date] NULL,
[Inact_Dt] [date] NULL,
[SLS_Dt] [date] NULL,
[Status] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Vend] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ContactVend] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[New_Rep] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Inplt_Src] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[InspTag] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSTag] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DS] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NsCd] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PrdCls] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PrdTyp] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StdCst] [float] NULL,
[DlrNet] [float] NULL,
[CnsLst] [float] NULL,
[OP] [float] NULL,
[EOQ] [float] NULL,
[PrtType] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OC] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SC] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PkgCd] [varchar] (11) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PkgQty] [float] NULL,
[X_PN] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[X_Comm] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[X_Combi] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[X_Alpha] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[X_SOH] [float] NOT NULL,
[X_PreRcpt] [float] NOT NULL,
[X_OO] [float] NOT NULL,
[X_SS] [float] NOT NULL,
[X_BO] [float] NOT NULL,
[X_Commtd] [float] NOT NULL,
[X_12_Mo_Usg] [float] NULL,
[X_12_Mo_Trans] [float] NULL,
[X_MTD_LE] [float] NOT NULL,
[X_MTD_LF] [float] NOT NULL,
[X_12_Mo_LE] [float] NOT NULL,
[X_12_Mo_LF] [float] NOT NULL,
[X_Lst_Rcpt_Dt] [date] NULL,
[X_Lst_Tran_Dt] [date] NULL,
[X_Origin_Dt] [date] NULL,
[X_Inact_Dt] [date] NULL,
[X_SLS_Dt] [date] NULL,
[X_Status] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[X_Vend] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[X_ContactVend] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[X_New_Rep] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[X_Inplt_Src] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[X_InspTag] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[X_RSTag] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[X_DS] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[X_NsCd] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[X_PrdCls] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[X_PrdTyp] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[X_StdCst] [float] NULL,
[X_DlrNet] [float] NULL,
[X_CnsLst] [float] NULL,
[X_OP] [float] NULL,
[X_EOQ] [float] NULL,
[X_PrtType] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[X_OC] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[X_SC] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[X_PkgCd] [varchar] (11) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[X_PkgQty] [float] NULL,
[Set_Alpha] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Set_SOH] [float] NULL,
[Set_PreRcpt] [float] NULL,
[Set_OO] [float] NULL,
[Set_SS] [float] NULL,
[Set_BO] [float] NULL,
[Set_Commtd] [float] NULL,
[Set_12_Mo_Usg] [float] NULL,
[Set_12_Mo_Trans] [float] NULL,
[Set_MTD_LE] [float] NULL,
[Set_MTD_LF] [float] NULL,
[Set_12_Mo_LE] [float] NULL,
[Set_12_Mo_LF] [float] NULL,
[Set_Lst_Rcpt_Dt] [date] NULL,
[Set_Lst_Tran_Dt] [date] NULL,
[Set_Mo_Av] [float] NULL,
[Set_Ld_Time] [float] NULL,
[Set_Vend] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
