CREATE TABLE [dbo].[dwn_pdc_NP_Vendor_Part_Number]
(
[VNVDNM] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VNVPNO] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VNVABR] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VNACCD] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VNPT15] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VNECN8] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VNPJNO] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VNVPTN] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VNVND6] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VNBUYR] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VNPRC] [float] NULL,
[VNCURC] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VNLDTM] [float] NULL,
[VNMQTY] [float] NULL,
[VNMDOL] [float] NULL,
[VNPRCD] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VNDISC] [float] NULL,
[VNSTS] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VNRELD] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VNNODT] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VNNOID] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VNCRDT] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VNCRID] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VNMNDT] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VNMNID] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VNNOMG] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VNMNPG] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VNNDDT] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
