CREATE TABLE [dbo].[wrk_RYOS_PDC_PN_Suppt_Req]
(
[PN] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[wrk_RYOS_PDC_PN_Suppt_Req] ADD CONSTRAINT [PK_ryos_suppt_req_tmp] PRIMARY KEY CLUSTERED ([PN]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [NonClusteredIndex-20220224-203652] ON [dbo].[wrk_RYOS_PDC_PN_Suppt_Req] ([PN]) ON [PRIMARY]
GO
