CREATE TABLE [dbo].[dwn_eng_Part_Master]
(
[BBB9CD] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[BBM8ST] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[BBABCD] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[BBBLCD] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[BBB6CD] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[BBB8CD] [varchar] (22) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[BBCBCD] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[BBGZCD] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[BBEVST] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[BBEWST] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[BBEXST] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[BBCKTX] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[BBCLTX] [float] NOT NULL,
[BBCMTX] [float] NOT NULL,
[BBCNTX] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[BBAODT] [float] NOT NULL,
[BBCQTX] [float] NOT NULL,
[BBAPDT] [float] NOT NULL,
[BBEYST] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[BBEZST] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[BBE0ST] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[BBAQDT] [float] NOT NULL,
[BBE1ST] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[BBAXNA] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[BBAYNA] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[BBAZNA] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[BBE2ST] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[BBE3ST] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[BBCYNB] [float] NOT NULL,
[BBIUST] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[BBD3NB] [float] NOT NULL,
[BBSFST] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[BBIWNB] [float] NOT NULL,
[BBK1TX] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[BBULST] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SOFTWARE_REQ] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
