CREATE TABLE [dbo].[zhose_test]
(
[Origin Dt] [date] NULL,
[Maint Dt] [date] NULL,
[Origin Date] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Maint Date] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Initials] [nvarchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Type] [nvarchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Vendor] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Prod #] [nvarchar] (14) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Hys #] [nvarchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Yal #] [nvarchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Asm L-# IN] [decimal] (7, 2) NULL,
[Asm L-# MM Not Rounded] [numeric] (11, 3) NULL,
[Rounded Asm L-# MM] [int] NULL,
[Tot Length] [varchar] (37) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Bulk #] [nvarchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comp1] [nvarchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Bulk HPN] [nvarchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comp1 HYS] [nvarchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Bulk YPN] [nvarchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comp1 YAL] [nvarchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Bulk Cut To-# IN] [decimal] (20, 4) NULL,
[Rounded Bulk Cut To-# IN] [decimal] (10, 2) NULL,
[Bulk L-# IN] [decimal] (10, 2) NULL,
[Comp1 CUT TO] [decimal] (10, 2) NULL,
[Bulk Cut To-# MM Not Rounded] [numeric] (24, 5) NULL,
[Rounded Bulk Cut To-# MM] [decimal] (10, 2) NULL,
[Bulk-# FT] [int] NULL,
[Comp1 Qty] [int] NULL,
[Bulk Comm] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comp1 Comm] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Die PN] [nvarchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Die HPN] [nvarchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Die YPN] [nvarchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Die Color] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comm1] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comm1 Hys] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comm1 Yal] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Ring PN] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Ring HPN] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Ring YPN] [nvarchar] (13) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Ring Color] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comm2] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comm2 Hys] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comm2 Yal] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Lt Ftg] [nvarchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Left Ftg Pusher PN] [nvarchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Left Ftg Pusher HPN] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Left Ftg Pusher YPN] [nvarchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Qty-Lt Ftg] [int] NULL,
[Ftg1] [nvarchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comp2] [nvarchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Ftg1 Hys #] [nvarchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comp2 Hys] [nvarchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Ftg1 Yal #] [nvarchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comp2 Yal] [nvarchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Ftg1 Qty] [int] NULL,
[Comp2 Qty] [int] NULL,
[Grd Placemt-# IN] [nvarchar] (24) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Grd Cut Comments] [nvarchar] (26) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Ftg1 Comm] [nvarchar] (29) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comp2 Comm] [nvarchar] (29) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Ftg1 Hys Comm] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comp2 Hys Comm] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Ftg1 Yal Comm] [nvarchar] (29) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comp2 Yal Comm] [nvarchar] (29) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Rt Ftg] [nvarchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Right Ftg Pusher PN] [nvarchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Right Ftg Pusher Hys] [nvarchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Right Ftg Pusher Yal] [nvarchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Qty-Rt Ftg] [int] NULL,
[Ftg2] [nvarchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comp3] [nvarchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Ftg2 Hys #] [nvarchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comp3 Hys] [nvarchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Ftg2 Yal #] [nvarchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comp3 Yal] [nvarchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Ftg2 Qty] [int] NULL,
[Comp3 Qty] [int] NULL,
[Ftg2 Comm] [nvarchar] (29) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comp3 Comm] [nvarchar] (29) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Ftg2 Hys Comm] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comp3 Hys Comm] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Ftg2 Yal Comm] [nvarchar] (29) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comp3 Yal Comm] [nvarchar] (29) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Guard #] [nvarchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comp4] [nvarchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comp4 Hys] [nvarchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comp4 Yal] [nvarchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Grd_Qty] [int] NULL,
[Comp4 Qty] [int] NULL,
[Tot Grd Cut To-# IN] [float] NULL,
[Tot Grd Cut To-# FT] [float] NULL,
[Comp4 Cut To] [float] NULL,
[Guard_Cut_Comments] [nvarchar] (26) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comm7] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Guard Comm] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comp4 Comm] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Print Or Chart] [nvarchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Print Or Chart Req] [nvarchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comm3] [nvarchar] (27) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Split Info] [nvarchar] (24) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comm4] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Other Req] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comm5] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Restrictions] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comm6] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Cap Or Plug] [varchar] (28) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comm8] [varchar] (28) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Eng Notes] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Ferrule1] [nvarchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comp5] [nvarchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Ferrule1 Hys #] [nvarchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comp5 HYS] [nvarchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Ferrule1 Yal #] [nvarchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comp5 YAL] [nvarchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Ferrule1 Qty] [int] NULL,
[Comp5 Qty] [int] NULL,
[Ferrule2] [nvarchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comp6] [nvarchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Ferrule2 Hys #] [nvarchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comp6 Hys] [nvarchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Ferrule2 Yal #] [nvarchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comp6 Yal] [nvarchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Ferrule2 Qty] [int] NULL,
[Comp6 Qty] [int] NULL
) ON [PRIMARY]
GO
