IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'GLOBAL\PDC_AMData_AMDC')
CREATE LOGIN [GLOBAL\PDC_AMData_AMDC] FROM WINDOWS
GO
CREATE USER [GLOBAL\PDC_AMData_AMDC] FOR LOGIN [GLOBAL\PDC_AMData_AMDC]
GO
