IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'GLOBAL\apkroth')
CREATE LOGIN [GLOBAL\apkroth] FROM WINDOWS
GO
CREATE USER [GLOBAL\apkroth] FOR LOGIN [GLOBAL\apkroth]
GO
GRANT DELETE TO [GLOBAL\apkroth]
GRANT INSERT TO [GLOBAL\apkroth]
GRANT SELECT TO [GLOBAL\apkroth]
GRANT UPDATE TO [GLOBAL\apkroth]
