IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'NMHGEXT\APCSEXTO')
CREATE LOGIN [NMHGEXT\APCSEXTO] FROM WINDOWS
GO
CREATE USER [NMHGEXT\APCSEXTO] FOR LOGIN [NMHGEXT\APCSEXTO]
GO
