CREATE USER [PDC_Extract] FOR LOGIN [PDC_Extract]
GO
GRANT CREATE TABLE TO [PDC_Extract]
GRANT CREATE VIEW TO [PDC_Extract]
GRANT DELETE TO [PDC_Extract]
GRANT EXECUTE TO [PDC_Extract]
GRANT INSERT TO [PDC_Extract]
GRANT SELECT TO [PDC_Extract]
GRANT UPDATE TO [PDC_Extract]
