GRANT SELECT ON SCHEMA:: [dbo] TO [GLOBAL\AP PDC Users]
GO
GRANT INSERT ON SCHEMA:: [dbo] TO [GLOBAL\apasmith]
GO
GRANT SELECT ON SCHEMA:: [dbo] TO [GLOBAL\apasmith]
GO
GRANT UPDATE ON SCHEMA:: [dbo] TO [GLOBAL\apasmith]
GO
GRANT EXECUTE ON SCHEMA:: [dbo] TO [GLOBAL\apcsmith]
GO
GRANT DELETE ON SCHEMA:: [dbo] TO [GLOBAL\apjdudle]
GO
GRANT INSERT ON SCHEMA:: [dbo] TO [GLOBAL\apjdudle]
GO
GRANT SELECT ON SCHEMA:: [dbo] TO [GLOBAL\apjdudle]
GO
GRANT UPDATE ON SCHEMA:: [dbo] TO [GLOBAL\apjdudle]
GO
GRANT CONTROL ON SCHEMA:: [dbo] TO [GLOBAL\APJFEING]
GO
GRANT DELETE ON SCHEMA:: [dbo] TO [GLOBAL\APJFEING]
GO
GRANT INSERT ON SCHEMA:: [dbo] TO [GLOBAL\APJFEING]
GO
GRANT REFERENCES ON SCHEMA:: [dbo] TO [GLOBAL\APJFEING]
GO
GRANT SELECT ON SCHEMA:: [dbo] TO [GLOBAL\APJFEING]
GO
GRANT UPDATE ON SCHEMA:: [dbo] TO [GLOBAL\APJFEING]
GO
GRANT ALTER ON SCHEMA:: [dbo] TO [GLOBAL\aprnewel]
GO
GRANT DELETE ON SCHEMA:: [dbo] TO [GLOBAL\aprnewel]
GO
GRANT EXECUTE ON SCHEMA:: [dbo] TO [GLOBAL\aprnewel]
GO
GRANT INSERT ON SCHEMA:: [dbo] TO [GLOBAL\aprnewel]
GO
GRANT SELECT ON SCHEMA:: [dbo] TO [GLOBAL\aprnewel]
GO
GRANT UPDATE ON SCHEMA:: [dbo] TO [GLOBAL\aprnewel]
GO
GRANT SELECT ON SCHEMA:: [dbo] TO [GLOBAL\PDC_AMData_Marketing]
GO
GRANT DELETE ON SCHEMA:: [dbo] TO [GLOBAL\PDC_AMData_Pune_Readiness]
GO
GRANT INSERT ON SCHEMA:: [dbo] TO [GLOBAL\PDC_AMData_Pune_Readiness]
GO
GRANT SELECT ON SCHEMA:: [dbo] TO [GLOBAL\PDC_AMData_Pune_Readiness]
GO
GRANT UPDATE ON SCHEMA:: [dbo] TO [GLOBAL\PDC_AMData_Pune_Readiness]
GO
